"use client";

import { motion } from "framer-motion";

function ScriptPreview() {
  return (
      <div className="rounded-3xl border border-black/10 bg-white p-6 shadow-sm">
            <div className="mb-4 flex items-center justify-between">
                    <div>
                              <p className="text-sm font-medium text-black/55">Sturdy response</p>
                                        <h3 className="text-lg font-semibold text-neutral-900">
                                                    Hard moment script
                                                              </h3>
                                                                      </div>
                                                                              <div className="rounded-full bg-neutral-100 px-3 py-1 text-xs font-medium text-neutral-700">
                                                                                        Regulate • Connect • Guide
                                                                                                </div>
                                                                                                      </div>

                                                                                                            <div className="space-y-4">
                                                                                                                    <div className="rounded-2xl bg-[#F5F8FF] p-4">
                                                                                                                              <p className="mb-1 text-sm font-semibold text-[#3157C7]">Regulate</p>
                                                                                                                                        <p className="text-sm leading-6 text-neutral-800">
                                                                                                                                                    You’re really upset that TV time ended.
                                                                                                                                                              </p>
                                                                                                                                                                      </div>

                                                                                                                                                                              <div className="rounded-2xl bg-[#F4FBF6] p-4">
                                                                                                                                                                                        <p className="mb-1 text-sm font-semibold text-[#2F8A57]">Connect</p>
                                                                                                                                                                                                  <p className="text-sm leading-6 text-neutral-800">
                                                                                                                                                                                                              You wanted more time, and stopping feels really hard. I’m not going
                                                                                                                                                                                                                          to let you hit.
                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                    <div className="rounded-2xl bg-[#FFF8EE] p-4">
                                                                                                                                                                                                                                                              <p className="mb-1 text-sm font-semibold text-[#A56A00]">Guide</p>
                                                                                                                                                                                                                                                                        <p className="text-sm leading-6 text-neutral-800">
                                                                                                                                                                                                                                                                                    TV is done. You can sit with me and calm your body, or we can walk
                                                                                                                                                                                                                                                                                                to your room together.
                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                              function ChatBoxPreview() {
                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                    <div className="rounded-3xl border border-black/10 bg-white p-4 shadow-sm">
                                                                                                                                                                                                                                                                                                                                          <div className="mb-3 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm font-medium text-black/55">Try Sturdy</p>
                                                                                                                                                                                                                                                                                                                                                                      <h3 className="text-base font-semibold text-neutral-900">
                                                                                                                                                                                                                                                                                                                                                                                  What’s happening right now?
                                                                                                                                                                                                                                                                                                                                                                                            </h3>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                            <div className="rounded-full bg-neutral-100 px-3 py-1 text-xs text-neutral-700">
                                                                                                                                                                                                                                                                                                                                                                                                                      Chat-style input
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="rounded-2xl bg-neutral-50 p-4 text-sm text-neutral-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  My 4-year-old is screaming and hitting because I turned off the TV.
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-3 text-xs text-neutral-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Describe the moment in one sentence.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="mt-4 w-full rounded-2xl bg-neutral-900 px-4 py-3 text-sm font-semibold text-white transition hover:bg-neutral-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Get script
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default function HeroSection() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <section className="relative overflow-hidden px-6 py-20 sm:px-8 lg:px-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    initial={{ opacity: 0, y: 18 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        transition={{ duration: 0.45, ease: "easeOut" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="inline-flex rounded-full border border-black/10 bg-white px-4 py-2 text-sm font-medium text-neutral-700 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Crisis-first parenting response tool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h1 className="mt-6 max-w-xl text-4xl font-semibold tracking-tight text-neutral-950 sm:text-5xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      What should I say right now?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-5 max-w-xl text-lg leading-8 text-neutral-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Sturdy gives parents calm, practical words for hard moments — fast.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-4 max-w-xl text-base leading-7 text-neutral-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Type what’s happening in a familiar chat-style box. Sturdy returns a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  grounded script that follows Regulate, Connect, and Guide.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-8 flex flex-wrap gap-3 text-sm text-neutral-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="rounded-full bg-neutral-100 px-4 py-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                No therapy jargon
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="rounded-full bg-neutral-100 px-4 py-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Age-adjusted
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="rounded-full bg-neutral-100 px-4 py-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Neurotype-aware
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="rounded-full bg-neutral-100 px-4 py-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Built for hard moments
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  initial={{ opacity: 0, y: 18 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition={{ duration: 0.5, delay: 0.08, ease: "easeOut" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="grid gap-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ChatBoxPreview />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ScriptPreview />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }