export const colors = {
  background: '#F7F9FC',
  surface: '#FFFFFF',
  primary: '#5B8DEF',
  primaryPressed: '#4B79D6',
  text: '#1E2430',
  textSecondary: '#4B5563',
  border: '#D7DFEA',
  chipBackground: '#EDF3FF',
  chipBorder: '#C7D8FB',
  successBackground: '#EEF6FF',
  softSectionBackground: '#EEF2FA',
  borderSoft: '#D9E2F2',
  borderSubtle: '#E6EBF5',
  cardBackground: '#FFFFFF',
  textPrimary: '#1A1F36',
  textMuted: '#8B95A7',
  success: '#7BCFA6',
  white: '#FFFFFF',
} as const;
